### ISSUE TITLE
Local Whisper Error

### ISSUE THREAD

**Issue by POD319** [ILikeAI/AlwaysReddy#25] opened 2024-05-01 20:53 UTC
I have a local Whisper install, so I tried to set the path in config.py

`> WHISPER_MODEL_PATH = C.../Whisper/models/ggml-base.en.bin`

Getting this error on start

Failed to start the recorder: [WinError 3] The system cannot find the path specified: 'C.../Whisper/models/ggml-base.en.bin\\models--Systran--faster-whisper-base'

Is it trying to add something at the end?

**Comment by zheroz00** [comment] 2024-05-02 17:00
Are there spaces in the path? It may need quotes around the path. Good luck.

**Comment by POD319** [comment] 2024-05-02 21:32
Thanks for the idea -- there are spaces, but I do already have quotes around it.

It seems like it's adding the ending bit from models--systran--faster-whisper-base
Going to see if I can figure it out, but if anyone has tested localwhisper, please let me know how it went for you.

**Comment by zheroz00** [comment] 2024-05-03 00:51
I think I got mine working. No errors anyway. What I did was download the whisper models via python like this.

import whisper
model = whisper.load_model("base")

Change the base to whichever you like, tiny, small, etc. That downloads the model and places it in "C:\Users\<username>\.cache\whisper\<model>"

From there I changed the line in the config to;
WHISPER_MODEL_PATH = "C:\\Users\\yourusername\\.cache\\whisper"

Saved it and ran it. I got a torch error saying it was newer than the req, but it still ran fine. The reason I mentioned that I'm not sure 100% if it's working is if these are the models that it was intended to use. If anyone can let me know, that'd be great.

**Comment by POD319** [comment] 2024-05-03 04:30
Interesting. Did you change the import in whisperx_api.py ? Mine has import whisperx as wx at the top, and I figure that is what is dictating the model.

No matter what I did, mine continuously adds models--Systran--faster-whisper-base to the end of my supplied path, as if that is the presumed model.

I ended up googling that and finding the model on huggingface, and put it in the same directory, and renamed it to models--Systran--faster-whisper-base.bin

The program now works, although I seemed forced to use that model.

Curious where you put your whisper import, as I'd love to use the model I already had downloaded. I get that same torch error, it looks like one of the includes is deprecated. If you are seeing the hotkey request though, you should be good.

You could try to disable your ethernet adapter and test to make sure its truly working locally as well.

**Comment by zheroz00** [comment] 2024-05-03 15:32
Let me do a bit of testing for you. I'll note my steps down and also do the network test. 

Josh mentioned today in a thread that he's working on a bunch of updates that should be ready around this time, including an updated install method. If you don't hear back from me by tomorrow, have a look and see if Josh has made any updates yet.

Similarly, if you get anything sorted out, let me know. 

cheers

**Comment by ILikeAI** [comment] 2024-05-03 23:32
My updates are still a few hours away, ill make an announcement in discord when they are up

**Comment by ILikeAI** [comment] 2024-05-04 07:31
Just merged!

**Comment by ILikeAI** [comment] 2024-05-07 11:29
I have just swapped away from the whisperX library, let me know if the bug persists

**Closed** 2024-05-07 11:29 UTC

**Comment by POD319** [comment] 2024-05-07 16:11
> I have just swapped away from the whisperX library, let me know if the bug persists

I see the `WHISPER_MODEL_PATH = ""` line was removed from the latest commit. Is there still support for running your own whisper model? Or do you need to use the inbuilt faster_whisper?

**Comment by POD319** [comment] 2024-05-13 19:13
> Sorry for the late response! Currently there is not support for pointing to your own model

No worries, appreciate the info. Related question - where is the faster-whisper model stored? I don't see it in the repo directory

**Comment by ILikeAI** [comment] 2024-05-20 04:44
The model files are kept in : AlwaysReddy\piper_tts
